# PREDICT THE BURNED AREA OF FOREST FIRES WITH NEURAL NETWORKS

IMPORTING THE NECESSARY LIBRARIES

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout

READING THE DATASET

In [2]:
df = pd.read_csv(r"C:\Users\Sujal Sahu\Downloads\forestfires (1).csv")

EDA

In [3]:
df.head()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small

In [21]:
df.tail()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
512,1,3,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,0,0
513,1,3,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,0,0
514,1,3,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,0,0
515,1,2,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,0,1
516,9,5,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,0,1,0,0,1

In [22]:
df.shape

(517, 31)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   month          517 non-null    int32
 1   day            517 non-null    int32
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64
 12  daymon         517 non-null    int64
 13  daysat         517 non-null    int64
 14  daysun         517 non-null    int64
 15  daythu         517 non-null    int64
 16  daytue         517 non-null    int64
 17  daywed         517 non-null    int64
 18  monthapr       517 non-null    int64
 19  monthaug       517 non-null    int64
 20  monthdec       517 non-null    int64
 21  monthfeb       517 non-null    int64
 22  monthjan       517 non-null    int64
 23  monthjul       517 non-null    int64
 24  monthjun       517 non-null    int64
 25  monthmar       517 non-null    int64
 26  monthmay       517 non-null    int64
 27  monthnov       517 non-null    int64
 28  monthoct       517 non-null    int64
 29  monthsep       517 non-null    int64
 30  size_category  517 non-null    int32
dtypes: float64(8), int32(3), int64(20)
memory usage: 119.3 KB

In [25]:
df.describe()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,...,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,5.758221,2.736944,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,...,0.038685,0.003868,0.061896,0.032882,0.104449,0.003868,0.001934,0.029014,0.332689,0.731141
std,4.373275,1.925061,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,...,0.193029,0.062137,0.241199,0.178500,0.306138,0.062137,0.043980,0.168007,0.471632,0.443796
min,0.000000,0.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6.000000,3.000000,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,11.000000,4.000000,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,11.000000,6.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
df['month']=label_encoder.fit_transform(df['month'])
df['day']=label_encoder.fit_transform(df['day'])
df['size_category']=label_encoder.fit_transform(df['size_category'])
df

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,7,0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,1
1,10,5,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,1
2,10,2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,1
3,7,0,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,1
4,7,3,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,1,3,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,0,0
513,1,3,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,0,0
514,1,3,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,0,0
515,1,2,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,0,1
516,9,5,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,0,1,0,0,1

SPLITTING THE DATA INTO DEPENDENT AND INDEPENDENT VARIABLE

In [13]:
X = df.drop(columns=['size_category'])
y = df['size_category']

In [14]:
X

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
0,7,0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,0,1,0,0,0,0
1,10,5,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,0,1,0
2,10,2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,0,1,0
3,7,0,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,0,1,0,0,0,0
4,7,3,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,1,3,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,0,0
513,1,3,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,0,0
514,1,3,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,0,0
515,1,2,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,0,0
516,9,5,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,0,0,1,0,0

In [15]:
y

0      1
1      1
2      1
3      1
4      1
      ..
512    0
513    0
514    0
515    1
516    1
Name: size_category, Length: 517, dtype: int32

SPLITTING THE DATA INTO TRAIN AND TEST SETS

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

BUILDING THE MODEL

In [17]:
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

COMPILING THE MODEL

In [26]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

TRAINING THE MODEL

In [27]:
model.fit(X_train, y_train, epochs=150, batch_size=9)

Epoch 1/150
46/46 [==============================] - 2s 3ms/step - loss: 0.1193 - accuracy: 0.9613
Epoch 2/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0753 - accuracy: 0.9685
Epoch 3/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0811 - accuracy: 0.9709
Epoch 4/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0657 - accuracy: 0.9758
Epoch 5/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0941 - accuracy: 0.9637
Epoch 6/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0963 - accuracy: 0.9588
Epoch 7/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0689 - accuracy: 0.9709
Epoch 8/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1131 - accuracy: 0.9685
Epoch 9/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0928 - accuracy: 0.9661
Epoch 10/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0962 - accuracy: 0.9564
Epoch 11/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1069 - accuracy: 0.9516
Epoch 12/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1397 - accuracy: 0.9467
Epoch 13/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0865 - accuracy: 0.9564
Epoch 14/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0950 - accuracy: 0.9588
Epoch 15/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1004 - accuracy: 0.9613
Epoch 16/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0943 - accuracy: 0.9661
Epoch 17/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0916 - accuracy: 0.9637
Epoch 18/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0649 - accuracy: 0.9734
Epoch 19/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0914 - accuracy: 0.9564
Epoch 20/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1601 - accuracy: 0.9419
Epoch 21/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1174 - accuracy: 0.9564
Epoch 22/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0993 - accuracy: 0.9661
Epoch 23/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0902 - accuracy: 0.9709
Epoch 24/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0822 - accuracy: 0.9637
Epoch 25/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1075 - accuracy: 0.9661
Epoch 26/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0960 - accuracy: 0.9564
Epoch 27/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1007 - accuracy: 0.9564
Epoch 28/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0853 - accuracy: 0.9685
Epoch 29/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0938 - accuracy: 0.9564
Epoch 30/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0871 - accuracy: 0.9685
Epoch 31/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0748 - accuracy: 0.9709
Epoch 32/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0891 - accuracy: 0.9685
Epoch 33/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1269 - accuracy: 0.9516
Epoch 34/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1012 - accuracy: 0.9564
Epoch 35/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0574 - accuracy: 0.9782
Epoch 36/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0804 - accuracy: 0.9685
Epoch 37/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0592 - accuracy: 0.9782
Epoch 38/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1170 - accuracy: 0.9540
Epoch 39/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1404 - accuracy: 0.9564
Epoch 40/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0698 - accuracy: 0.9709
Epoch 41/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0999 - accuracy: 0.9637
Epoch 42/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0984 - accuracy: 0.9540
Epoch 43/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1351 - accuracy: 0.9588
Epoch 44/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1097 - accuracy: 0.9613
Epoch 45/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0849 - accuracy: 0.9661
Epoch 46/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1200 - accuracy: 0.9588
Epoch 47/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0764 - accuracy: 0.9758
Epoch 48/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0827 - accuracy: 0.9637
Epoch 49/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0693 - accuracy: 0.9782
Epoch 50/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0852 - accuracy: 0.9758
Epoch 51/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0825 - accuracy: 0.9709
Epoch 52/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1223 - accuracy: 0.9516
Epoch 53/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1154 - accuracy: 0.9637
Epoch 54/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1509 - accuracy: 0.9492
Epoch 55/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1116 - accuracy: 0.9588
Epoch 56/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0927 - accuracy: 0.9685
Epoch 57/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1081 - accuracy: 0.9661
Epoch 58/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1064 - accuracy: 0.9564
Epoch 59/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1290 - accuracy: 0.9588
Epoch 60/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1221 - accuracy: 0.9588
Epoch 61/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0758 - accuracy: 0.9637
Epoch 62/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1146 - accuracy: 0.9516
Epoch 63/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1182 - accuracy: 0.9613
Epoch 64/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0966 - accuracy: 0.9661
Epoch 65/150
46/46 [==============================] - 0s 2ms/step - loss: 0.1754 - accuracy: 0.9443
Epoch 66/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0903 - accuracy: 0.9685
Epoch 67/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0904 - accuracy: 0.9685
Epoch 68/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0763 - accuracy: 0.9758
Epoch 69/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0613 - accuracy: 0.9709
Epoch 70/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0966 - accuracy: 0.9685
Epoch 71/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0562 - accuracy: 0.9855
Epoch 72/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0628 - accuracy: 0.9831
Epoch 73/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0889 - accuracy: 0.9588
Epoch 74/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1225 - accuracy: 0.9492
Epoch 75/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1310 - accuracy: 0.9540
Epoch 76/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1067 - accuracy: 0.9588
Epoch 77/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1020 - accuracy: 0.9734
Epoch 78/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1152 - accuracy: 0.9516
Epoch 79/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1072 - accuracy: 0.9613
Epoch 80/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1101 - accuracy: 0.9661
Epoch 81/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0863 - accuracy: 0.9637
Epoch 82/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0834 - accuracy: 0.9709
Epoch 83/150

46/46 [==============================] - 0s 3ms/step - loss: 0.1081 - accuracy: 0.9613
Epoch 84/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0813 - accuracy: 0.9709
Epoch 85/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1006 - accuracy: 0.9588
Epoch 86/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0839 - accuracy: 0.9782
Epoch 87/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0905 - accuracy: 0.9637
Epoch 88/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0967 - accuracy: 0.9588
Epoch 89/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0611 - accuracy: 0.9758
Epoch 90/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1049 - accuracy: 0.9588
Epoch 91/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0825 - accuracy: 0.9588
Epoch 92/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0660 - accuracy: 0.9782
Epoch 93/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0985 - accuracy: 0.9685
Epoch 94/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0897 - accuracy: 0.9709
Epoch 95/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0992 - accuracy: 0.9685
Epoch 96/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0627 - accuracy: 0.9734
Epoch 97/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0526 - accuracy: 0.9855
Epoch 98/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0852 - accuracy: 0.9709
Epoch 99/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0732 - accuracy: 0.9709
Epoch 100/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0742 - accuracy: 0.9782
Epoch 101/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0567 - accuracy: 0.9855
Epoch 102/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0864 - accuracy: 0.9685
Epoch 103/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1003 - accuracy: 0.9685
Epoch 104/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0693 - accuracy: 0.9806
Epoch 105/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0863 - accuracy: 0.9588
Epoch 106/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0871 - accuracy: 0.9613
Epoch 107/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0993 - accuracy: 0.9637
Epoch 108/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1859 - accuracy: 0.9564
Epoch 109/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1436 - accuracy: 0.9395
Epoch 110/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1084 - accuracy: 0.9564
Epoch 111/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0664 - accuracy: 0.9782
Epoch 112/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0560 - accuracy: 0.9806
Epoch 113/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0658 - accuracy: 0.9734
Epoch 114/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0918 - accuracy: 0.9564
Epoch 115/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0606 - accuracy: 0.9734
Epoch 116/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0552 - accuracy: 0.9831
Epoch 117/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0866 - accuracy: 0.9758
Epoch 118/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0914 - accuracy: 0.9661
Epoch 119/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0663 - accuracy: 0.9734
Epoch 120/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0913 - accuracy: 0.9782
Epoch 121/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0521 - accuracy: 0.9831
Epoch 122/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0670 - accuracy: 0.9758
Epoch 123/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0844 - accuracy: 0.9709
Epoch 124/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0540 - accuracy: 0.9782
Epoch 125/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0966 - accuracy: 0.9661
Epoch 126/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0705 - accuracy: 0.9685
Epoch 127/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0747 - accuracy: 0.9758
Epoch 128/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0522 - accuracy: 0.9782
Epoch 129/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0430 - accuracy: 0.9855
Epoch 130/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0762 - accuracy: 0.9709
Epoch 131/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0556 - accuracy: 0.9758
Epoch 132/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0754 - accuracy: 0.9661
Epoch 133/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0559 - accuracy: 0.9831
Epoch 134/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0708 - accuracy: 0.9685
Epoch 135/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0907 - accuracy: 0.9661
Epoch 136/150
46/46 [==============================] - 0s 3ms/step - loss: 0.1047 - accuracy: 0.9637
Epoch 137/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0995 - accuracy: 0.9637
Epoch 138/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0709 - accuracy: 0.9734
Epoch 139/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0514 - accuracy: 0.9734
Epoch 140/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0462 - accuracy: 0.9879
Epoch 141/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0642 - accuracy: 0.9758
Epoch 142/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0534 - accuracy: 0.9879
Epoch 143/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0983 - accuracy: 0.9588
Epoch 144/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0726 - accuracy: 0.9661
Epoch 145/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0711 - accuracy: 0.9685
Epoch 146/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0591 - accuracy: 0.9758
Epoch 147/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0876 - accuracy: 0.9685
Epoch 148/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0761 - accuracy: 0.9734
Epoch 149/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0603 - accuracy: 0.9782
Epoch 150/150
46/46 [==============================] - 0s 3ms/step - loss: 0.0651 - accuracy: 0.9734

EVALUATING THE MODEL

In [28]:
score = model.evaluate(X_test, y_test, batch_size=9)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

12/12 [==============================] - 0s 3ms/step - loss: 0.0327 - accuracy: 0.9808
Test loss: 0.03271665424108505
Test accuracy: 0.9807692170143127